import {Server} from 'socket.io'
import http from 'http'
import express from 'express'

const app=express()

const server=http.createServer(app)

const io=new Server(server,{
    cors:{
        origin:['http://localhost:5173'],
    }
})

//used to store online users
const userSocketMap={}  //{userId:socketId}{userId will be coimg from DB and socketId will be generated by socket.io}   
io.on('connection',(socket)=>{
    console.log("A user just connected",socket.id)

    const userId=socket.handshake.query.userId;
    if(userId){
        userSocketMap[userId]=socket.id //if user is connected we will add his id to userSocketMap
    }

    //io.emit() will send message to all connected users
    io.emit("getOnlineUsers",Object.keys(userSocketMap))

    socket.on('disconnect',()=>{
        console.log("A user just disconnected",socket.id)
        delete userSocketMap[userId] //if user is disconnected we will delete his id from userSocketMap
        io.emit("getOnlineUsers",Object.keys(userSocketMap))
    })

})

export {io,app,server}